version: "3.9"

services:
  payapp:
    build: .
    ports:
      - "80:8080"
  postgres:
    image: "docker.io/postgres:17.2-alpine3.21"
    environment:
      POSTGRES_DB: "bla"
      POSTGRES_PASSWORD: "bla"
    ports:
      - "5432:5432"